language: objective-c
osx_image: xcode11.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

addons:
  ssh_known_hosts: github.com

notifications:
  email: false

before_install:
  - env
  - locale
  - brew install git-lfs
  - git lfs install
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

before_script:
  - git lfs pull

script:
  - set -o pipefail

  - echo Check if the library described by the podspec can be built
  # Run full subspecs linting consuming too much of build time because CocoaPods use source code of Pods
  # Since`libx265` && `libde265` is Pod and have their own linting, don't waste time to lint full subspecs combination
  - pod lib lint --use-libraries --allow-warnings --no-subspecs --fail-fast

  - echo Build example
  - pod install --project-directory=Example
  - xcodebuild build -workspace Example/SDWebImageAVIFCoder.xcworkspace -scheme 'SDWebImageAVIFCoder-Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro' -configuration Debug | xcpretty -c
  - xcodebuild build -workspace Example/SDWebImageAVIFCoder.xcworkspace -scheme 'SDWebImageAVIFCoder-Example macOS' -sdk macosx -configuration Debug | xcpretty -c
  - xcodebuild build -workspace Example/SDWebImageAVIFCoder.xcworkspace -scheme 'SDWebImageAVIFCoder_Example CLI' -sdk macosx -configuration Debug | xcpretty -c

  - echo Clean builds
  - rm -rf ~/Library/Developer/Xcode/DerivedData/

  - echo Run unit tests
  - xcodebuild clean build test -workspace Example/SDWebImageAVIFCoder.xcworkspace  -scheme "SDWebImageAVIFCoder-Example" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro' -enableCodeCoverage 'YES' -configuration Debug | xcpretty -c

after_success:
    - bash <(curl -s https://codecov.io/bash) -D '~/Library/Developer/Xcode/DerivedData/' -J '^SDWebImageAVIFCoder$' -c -X gcov -F ios

